---
day1_input: |-
  1abc2
  pqr3stu8vwx
  a1b2c3d4e5f
  treb7uchet

day1_input_part2: |-
  two1nine
  eightwothree
  abcone2threexyz
  xtwone3four
  4nineeightseven2
  zoneight234
  7pqrstsixteen


# Some example input that helped me. Ensure that this matches "eight" not "one" in the firsts line
# Should be 155, NOT 142
# day1_input_part2: |-
#   sevenhk5oneight
#   ilk7gfive7


...
